---
title: Graphing the weather
hero_image: images/banner.png
description: Learn how to plot graphical weather data from the Raspberry Pi Weather
  Station database
original_url: https://raspberrypi.org/learning/graphing-the-weather
theme: red
duration: 2
listed: false
ingredient: false
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: ''
technologies: rpi, physical computing, python
site_areas: ''
steps:
- title: Introduction
- title: What you will need
- title: Graphing the weather
- title: Choosing a Weather Station
- title: Getting ready
- title: Fetching your first data set
- title: Looking at JSON
- title: Getting the time and temperature
- title: list comprehension to get all the temperatures in a list in a readable format
- title: Graphing the data
- title: What next?
- title: Graphing the weather
- title: Finding more pages
- title: Fetching all the pages
- title: Limiting the data downloaded
- title: Finishing off with a graph
- title: What next?

